# Machine Learning Basics

This notebook contains my elaboration on the mathematics behind machine learning. I will be discussing the following topics:
1. Linear Algebra
2. Statistics
3. Probability
4. Regression
5. Classification
6. Decision Trees

and more. I will be using Python to demonstrate the concepts.

## Linear Algebra

Let's start with complete basics, with a **VECTOR**.

A ***vector*** is a representation of a point in space. A vector can be defined in 1D and 2D spaces also, but its real significance comes only when it is defined in a 3D space, i.e., using **x**, **y** & **z** coordinate system.

An important point to note is that these *x*, *y* & *z* coordinates may or may not be independant of each other. But, for learning's sake, let's assume that they are independant.
Since they carry no relation with each other, we can write them in a ***column matrix***.

### What is a Matrix??

A ***matrix*** is a tabular representation of numbers, separated by space. These numbers, individually, may not contain any significance (not in our case, as they are coordinates) but inside a matrix, they carry many notable and important properties.

Let's take an example:

Assume your home is at the center as this is your current position. Let's set its coordinate to 0.
Now, you have to go to your school. Assuming your home and school lie on a straight line, the distance between your home and your school will be the co-ordinate of your school. Suppose the distance between your home and school is 4 km, its matrix representation will be as:

$$ [4] $$

But, in the real world, that is not the case, your home does not necessarily lie on the same straight line as your school, so what will be its coordinates??

Let's assume you have to travel 5 km in north and 3 km in east to get to your school. Then these will be the "**x**" and "**y**" coordinates of your school. The matrix representation of these will look like:

$$ \
\begin{bmatrix}
5 \\
3
\end{bmatrix}
$$

#### Types of Matrices

There are many types of matrices, but the most important ones are:
1. **Row Matrix**: A matrix with only one row. For example, $$ [1, 2, 3] $$
2. **Column Matrix**: A matrix with only one column. For example, $$ \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} $$
3. **Square Matrix**: A matrix with the same number of rows and columns. For example, $$ \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$
4. **Diagonal Matrix**: A matrix with all elements zero except the diagonal elements. For example, $$ \begin{bmatrix} 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 3 \end{bmatrix} $$
5. **Identity Matrix**: A matrix with all diagonal elements as 1 and all other elements as 0. For example, $$ \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} $$
6. **Scalar Matrix**: A matrix with all diagonal elements as the same number and all other elements as 0. For example, $$ \begin{bmatrix} 2 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2 \end{bmatrix} $$
7. **Singular Matrix**: A matrix whose determinant is 0. For example, $$ \begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix} $$
8. **Non-Singular Matrix**: A matrix whose determinant is not 0. For example, $$ \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$

Coming back to our vector discussion, let's see how we can represent a vector in Python.

In [3]:
# We use Numpy library for mathematical operations in Python

%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: C:\Users\chitr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


***What happened above??***

In programming, when we represent multiple numbers, we use a **list**. This list can be of any "dimension", i.e., it can be a 1D list, 2D list, 3D list, and so on.

That's too many new terms, right?? Let's address them one by one:

1. **List**: a collection of items separated by commas and enclosed within square brackets. For example, $$ [1, 2, 3] $$ is a list of 3 items. Programmers also call it an array.

2. **Dimension**: A dimension is something that can be measured by a single number. For example, a line is 1D, a square is 2D, and a cube is 3D. In programming, we can represent these dimensions using lists. For example, $$ [1, 2, 3] $$ is a 1D list, $$ \begin{bmatrix} [1] \\ [2] \\ [3] \end{bmatrix} $$ is a 2D list, and $$ \begin{bmatrix} [1 & 2 & 3] \\ [4 & 5 & 6] \\ [7 & 8 & 9] \end{bmatrix} $$ is a 3D list.


Let's talk about **Matrix Operations** now.
These matrices perform all the regular operations that we perform in mathematics, like addition, subtraction, multiplication except division. Division is not possible in matrices.

### Matrix Addition

Matrix addition is the addition of two matrices. The sum of two matrices is obtained by adding the corresponding elements of the two matrices. The sum of two matrices A and B is a matrix C. Each element of matrix C is the sum of the corresponding elements of matrix A and matrix B.

For example, let's take two matrices A and B:

$$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$
$$ B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} $$

The sum of these two matrices will be:

$$ C = \begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix} $$

### Matrix Subtraction

Matrix subtraction is the subtraction of two matrices. The difference of two matrices A and B is a matrix C. Each element of matrix C is the difference of the corresponding elements of matrix A and matrix B.

For example, let's take two matrices A and B:

$$ A = \begin{bmatrix} 10 & 12 \\15 & 20 \end{bmatrix} $$
$$ B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} $$

The difference of these two matrices will be:

$$ C = \begin{bmatrix} 10-5 & 12-6 \\ 15-7 & 20-8 \end{bmatrix} = \begin{bmatrix} 5 & 6 \\ 8 & 12 \end{bmatrix} $$

### Matrix Multiplication

Matrix multiplication is the multiplication of two matrices. The product of two matrices A and B is a matrix C. Each element of matrix C is the sum of the product of the corresponding elements of the ith row of matrix A and the jth column of matrix B.

> **Note**: 
> 1. The number of columns in the first matrix must be equal to the number of rows in the second matrix.
> 2. All Matrices are represented in (Row x Column) format. For example, a 2x3 matrix has 2 rows and 3 columns.
> 3. The resultant matrix will have the same number of rows as the first matrix and the same number of columns as the second matrix.

For example, let's take two matrices A and B with dimensions 2x3 and 3x2 respectively, the important point to note here is that the number of columns in A is equal to the number of rows in B.

$$ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} $$
$$ B = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix} $$

The product of these two matrices will be:

$$ C = \begin{bmatrix} 1*7+2*9+3*11 & 1*8+2*10+3*12 \\ 4*7+5*9+6*11 & 4*8+5*10+6*12 \end{bmatrix} = \begin{bmatrix} 58 & 64 \\ 139 & 154 \end{bmatrix} $$

You can see the multiplication visually happening on this [website](https://matrixmultiplication.xyz/).

### Determinant of a Matrix

The determinant of a matrix is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the matrix. The determinant of a matrix A is denoted as |A| or det(A).

To calculate the determinant of a 2x2 matrix, you need to subtract the product of the diagonals. For example, let's take a matrix A:

$$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$

The determinant of this matrix will be:

$$ |A| = 1*4 - 2*3 = 4 - 6 = -2 $$

To calculate the determinant of a 3x3 matrix, you need to subtract the product of the diagonals of the matrix. For example, let's take a matrix A:

$$ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} $$

The determinant of this matrix will be:

$$
|A| = 1*(5*9 - 6*8) - 2*(4*9 - 6*7) +  3*(4*8 - 5*7) \\
= 1*(45 - 48) - 2*(36 - 42) + 3*(32 - 35) \\
= 1*(-3) - 2*(-6) + 3*(-3) \\
= -3 + 12 - 9 = 0
$$

Fun Fact: Since the determinant of this matrix is 0, it is singular.

Let's see how we can perform these operations in Python.

In [6]:
# Matrix operations
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# Matrix Addition
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum = arr + mat
print(sum)

# Matrix Subtraction
sub = arr - mat
print(sub)

# Matrix Multiplication
mul = arr * mat
print(mul)

# Determinant
det = np.linalg.det(arr)
print(det)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
0.0


### Inverse of a Matrix

The inverse of a matrix is a matrix that, when multiplied with the original matrix, gives an identity matrix. The inverse of a matrix A is denoted as A^-1.